name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main
    paths:
      - '!README.md'
  pull_request_review:
    types: [submitted]

  workflow_dispatch:
  
jobs:
  check_pull_request_review:
    runs-on: ubuntu-latest
    name: Check Pull Request Review
    steps:
      - name: Check if PR is approved
        if: github.event.pull_request.base.ref == 'main'
        run: |
          APPROVED=$(jq -r '.review.state' "$GITHUB_EVENT_PATH")
          if [ "$APPROVED" != "approved" ]; then
            echo "Pull request not approved. Exiting with failure."
            exit 1
          fi
      
  block_pull_request_merge:
    runs-on: ubuntu-latest
    name: Block Pull Request Merge
    needs: check_pull_request_review
    if: failure()
    steps:
      - name: Fail workflow
        run: exit 1

  create_conda_environment:
    runs-on: ubuntu-latest
    name: Create Conda Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint_code:
    runs-on: ubuntu-latest
    name: Lint Code
    needs: create_conda_environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Lint Python code
        run: flake8 .
